// scripts/soul-status.ts
//
// Scans cards/*.md for soul sections and prints a per-card status line:
//   pending     — no card_soul.* sections
//   drafted     — at least one card_soul.* section, but not all six
//   merged      — all six soul sections present and parse cleanly
//   broken      — at least one section present but JSON parse fails
//
// Doesn't query Postgres. For DB ↔ markdown parity, use
// `npm run db:verify-cards-soul`.
//
// Usage:
//   npm run cards:soul-status              — print summary table
//   npm run cards:soul-status -- --md      — emit a fresh cards/_SOUL_STATUS.md
//   npm run cards:soul-status -- --json    — emit JSON

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const CARDS_DIR = join(ROOT, "cards");
const STATUS_PATH = join(CARDS_DIR, "_SOUL_STATUS.md");

const SOUL_SECTIONS = [
  "credit_score",
  "annual_credits",
  "insurance",
  "program_access",
  "co_brand_perks",
  "absent_perks",
] as const;

type SoulSection = (typeof SOUL_SECTIONS)[number];
type Status = "pending" | "drafted" | "merged" | "broken";

interface CardStatus {
  card_id: string;
  filename: string;
  status: Status;
  sections_present: SoulSection[];
  json_errors: string[];
  last_modified: string;
}

function listCardFiles(): string[] {
  return readdirSync(CARDS_DIR)
    .filter((f) => f.endsWith(".md") && f !== "AllCards.md" && !f.startsWith("_"))
    .sort();
}

function inspect(filename: string): CardStatus {
  const path = join(CARDS_DIR, filename);
  const md = readFileSync(path, "utf8");
  const card_id = filename.replace(/\.md$/, "");
  const stat = statSync(path);
  const last_modified = stat.mtime.toISOString().slice(0, 10);

  const lines = md.split("\n");
  const present: SoulSection[] = [];
  const errors: string[] = [];

  let inSection: SoulSection | null = null;
  let inFence = false;
  let buf: string[] = [];

  for (const line of lines) {
    // Section heading
    const m = line.match(/^## card_soul\.(\w+)\b/);
    if (m) {
      const key = m[1] as SoulSection;
      if (SOUL_SECTIONS.includes(key)) {
        if (!present.includes(key)) present.push(key);
        inSection = key;
      } else {
        inSection = null;
      }
      inFence = false;
      buf = [];
      continue;
    }
    if (line.startsWith("## ")) {
      inSection = null;
      continue;
    }
    if (!inSection) continue;

    if (line.startsWith("```json")) {
      inFence = true;
      buf = [];
      continue;
    }
    if (line.startsWith("```") && inFence) {
      try {
        JSON.parse(buf.join("\n"));
      } catch (e) {
        errors.push(`${inSection}: ${(e as Error).message}`);
      }
      inFence = false;
      buf = [];
      continue;
    }
    if (inFence) buf.push(line);
  }

  let status: Status;
  if (errors.length) status = "broken";
  else if (present.length === 0) status = "pending";
  else if (present.length >= SOUL_SECTIONS.length) status = "merged";
  else status = "drafted";

  return {
    card_id,
    filename,
    status,
    sections_present: present,
    json_errors: errors,
    last_modified,
  };
}

function main(): void {
  const wantMd = process.argv.includes("--md");
  const wantJson = process.argv.includes("--json");

  const files = listCardFiles();
  const all: CardStatus[] = files.map(inspect);

  const counts = {
    merged: all.filter((c) => c.status === "merged").length,
    drafted: all.filter((c) => c.status === "drafted").length,
    broken: all.filter((c) => c.status === "broken").length,
    pending: all.filter((c) => c.status === "pending").length,
    total: all.length,
  };

  if (wantJson) {
    console.log(JSON.stringify({ counts, cards: all }, null, 2));
    return;
  }

  // Build markdown table
  const lines: string[] = [];
  lines.push("# Soul status");
  lines.push("");
  lines.push(`Auto-generated by \`npm run cards:soul-status -- --md\`. Do not edit by hand.`);
  lines.push("");
  lines.push(`Last refreshed: ${new Date().toISOString()}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- **Merged:** ${counts.merged} / ${counts.total}`);
  lines.push(`- **Drafted (in progress):** ${counts.drafted}`);
  lines.push(`- **Broken (JSON parse fail):** ${counts.broken}`);
  lines.push(`- **Pending:** ${counts.pending}`);
  lines.push("");
  lines.push("## Per-card status");
  lines.push("");
  lines.push("| Status | Card | Sections | Last modified |");
  lines.push("|---|---|---|---|");

  // Sort: broken first (need attention), then drafted, then merged, then pending
  const order: Record<Status, number> = { broken: 0, drafted: 1, merged: 2, pending: 3 };
  const sorted = [...all].sort((a, b) => {
    const so = order[a.status] - order[b.status];
    return so !== 0 ? so : a.card_id.localeCompare(b.card_id);
  });

  for (const c of sorted) {
    const icon = c.status === "merged" ? "✅" : c.status === "drafted" ? "🟡" : c.status === "broken" ? "❌" : "⚪";
    const sections = c.sections_present.length > 0 ? c.sections_present.join(", ") : "—";
    lines.push(`| ${icon} ${c.status} | \`${c.card_id}\` | ${sections} | ${c.last_modified} |`);
  }

  lines.push("");
  if (counts.broken > 0) {
    lines.push("## Broken cards (JSON parse failures)");
    lines.push("");
    for (const c of all.filter((x) => x.status === "broken")) {
      lines.push(`### \`${c.card_id}\``);
      lines.push("");
      for (const e of c.json_errors) lines.push(`- ${e}`);
      lines.push("");
    }
  }

  const out = lines.join("\n") + "\n";

  if (wantMd) {
    writeFileSync(STATUS_PATH, out, "utf8");
    console.log(`Wrote ${STATUS_PATH}`);
    console.log(`Soul: ${counts.merged}/${counts.total} merged, ${counts.drafted} drafted, ${counts.broken} broken, ${counts.pending} pending.`);
  } else {
    console.log(out);
  }
}

main();
